### ISSUE TITLE
Can we prevent users from messing with their local storage?

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#104]
This doesn't need to be bulletproof, just inconvenient enough for users to change their data.

Here is the reason:

In a future iteration, we could do the following: For any users that have answered several questions with a specific accuracy, we will present a "magic button" that will take them to a private assessment.

The private assessment will consist of questions that users can answer, and we will share their email addresses with companies looking for candidates.

There are a lot of details to think through this, but I figure something we can ensure now is to prevent people from spoofing their local data too easily.

**Comment by haltakov** [comment]
We can sign the local storage content, include the signature with it and check it. The minified and packed JS code is actually quite obfuscated, so it will probably not be easy to find the method and the key.

We can even do the signing in the backend, but it will be more effort.

However, I'm not sure that it makes sense... I think if somebody wants to cheat, they will probably just open the site in a private tab, see the answer and then go back to answer correctly. This seems easier than fiddling with the local storage.

I have another proposal - we could try collecting some statistics about how "human" the interaction was. For example, did the user answer the question 5 seconds after they received it for the first time? Was the user moving the mouse/scrolling/swiping? Maybe even if there were two POST requests from the same IP address (this will require backend support as well). We can compute these metrics and store them in the local storage in an encrypted/obfuscated manner and use them later.

**Comment by svpino** [comment]
I'm not concerned about something cheating one question. I don't want people to go and change their history to get a specific benefit.

Here is what I'm thinking:

Let's say we agree with Company A to send them good leads. We **secretly** update the code to display a button for those who have answered 30 questions with at least 90% accuracy.

We don't announce this. Nobody knows that this is happening or how it is happening. 

Some people see the button, go down that rabbit hole, and then talk publicly about it. I want to avoid someone from messing with their historical data to get the button to show.

Makes sense?

Yes, they can still cheat a question and do that in perpetuity, but that's a much higher barrier.

**Comment by haltakov** [comment]
Ok, this is exactly how I imagined it showing a button to some people. I see your point now - we want to ensure that few people are able to cheat their way into getting the history right.

We can then add a signature to the local storage that is checked to verify it is legit. The code to encrypt it and the key will be in the frontend code, so it will be theoretically possible to find it, however, practically it is not easy since the JS code is quite obfuscated.

Do you think this will be enough?

**Comment by svpino** [comment]
That should be fine.

(There's an argument to be made for people who modify their history AFTER we make it hard — they are smart. They should probably deserve to see the button.)
