### ISSUE TITLE
Publish website under bnomial.com

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#112]
Let me know what do I need to do in the DNS console to redirect bnomial.com to our site.

**Comment by haltakov** [comment]
You should be able to do it from the Amplify settings: https://console.aws.amazon.com/amplify/home?region=us-east-1&code=7fa7feae2f538f2957d9#/d1dukld859gpsj/settings/domains

Btw. if we want to protect the content of some branch or even the main website, Amplify offers creating password protection :)

**Comment by haltakov** [comment]
It seems that the domain needs to be configured in Route53. We will need to adapt the analytics as well, but this is easy once we are live at bnomial.com

**Comment by svpino** [comment]
This is done.
