### ISSUE TITLE
Prepare bnomial Twitter account

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#113]

**Comment by svpino** [comment]
The account is created (@bnomialml — "bnomial" was already taken.) 

Next step is to update the logo, background, and bio.

**Comment by svpino** [comment]
@haltakov when you have time, please send me the logo SVG so I can start putting it everywhere :)

**Comment by haltakov** [comment]
Now I'm at my laptop, here is the link: https://github.com/underfitted/bnomial-daily/blob/main/public/icon.svg
