### ISSUE TITLE
Plausible - Custom goals

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#114]
Can we call the goals like this?

* Answered questions
* Sponsorship clickthrough

Since this is going to be public, I want to make sure these goals are obvious for everyone who sees them.

**Comment by haltakov** [comment]
I can easily rename the first one. The second one is built-in feature from Plausible, but I can also easily track the clicks manually. I'll do that tomorrow

**Comment by svpino** [comment]
Also, make sure you use bnomial.com now.
