### ISSUE TITLE
Is there anything we can tackle from the PageSpeed Insights?

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#127]
[Here is the report.](https://pagespeed.web.dev/report?url=http%3A%2F%2Fwww.bnomial.com&utm_source=google_domains&utm_medium=product&utm_campaign=website_card&hl=en-US)

Current performance:
* Desktop: 96%
* Mobile: 81%

What can we do to improve as long as it doesn't take too much time?

Anything too complex we can move to Season 2.

**Comment by haltakov** [comment]
Looking into some quick wins here
