### ISSUE TITLE
The time doesn't show after it reset

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#143]
For me, UTC 00:00:00 is at 7:00pm EST.

I took a look at 7:15pm and realized that the time until next question didn't show:

![image](https://user-images.githubusercontent.com/1126730/156377970-d3b2fe7f-0b6e-48e6-9c9e-7c37db4ad497.png)

This was using the progressive app. I tried with Safari as well and the same happened.

Couldn't try from a desktop because I was outside.

**Comment by haltakov** [comment]
Hmm, you mean you tried this on your iPhone with the app added on the home screen?

I just tried that and it works for me. I just pushed an update of the counter mechanism, but it worked before that as well. Can it be that you didn't have internet connection?

**Comment by haltakov** [comment]
Oh, OK... Can it be that the app was opened during the transition? I guess we are not handling this correctly yet, so I'll take a look.

**Comment by haltakov** [comment]
Should be fixed now with #145. I tested it with the fake API, but let's do a real test tonight :)
