### ISSUE TITLE
Sponsorships too complex?

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#151]
I've been thinking about the plan we have for sponsorships. I've shown a couple of people, and they are confused about the week vs. weekend. 

My thought process was: "$1,000 x 52 weeks = $52,000 if we sell out" but if we do this thing on the weekend our ceiling is way higher.

But I'm afraid I made it too complicated, and I'm also making a dumb assumption: price won't always be $1,000 x week. We will grow it as our audience increases.

So I'm considering simplifying the whole thing and keeping $1,000 x week (7 days.) That's it.

What do you think? @haltakov

**Comment by haltakov** [comment]
I liked having something interesting in the sponsorship model, but I get how this may be difficult to understand.

We can start with $1000 x 7 days, but I would still keep the weekend thing in the code. At some point, we can decide to enable it and effectively raise our prices ($1000 will now buy you only 5 days + some visibility on the weekend).

**Comment by haltakov** [comment]
This is how the website would look if we remove the weekend sponsor. Let me know if you want some more changes.

**Comment by svpino** [comment]
We need to update the text.

You can use this one below:

### Exclusive week sponsorships

This is the most effective way to promote your product or service to our audience of data scientists and machine learning professionals.

When you buy an exclusive week sponsorship, your logo and product or service description will be in the site's sidebar during the entire week. You won't share the spotlight with anyone else during this time. Your sponsorship will be the only one our users see.

Price: $1,000
Upcoming availability
...

**Comment by haltakov** [comment]
Oh you are right, I totally forgot to remove the sentence about the weekend roster... 🤦‍♂️ Fixed now.
