### ISSUE TITLE
Preview questions from JSON

### ISSUE THREAD

**Issue by haltakov** [underfitted/bnomial-daily#161]
Create a page to preview a whole question using the JSON from the DynamoDB.

**Comment by svpino** [comment]
Let's call this page `/contributions`.

I was planning to have a `contributions` page for Season 2. The goal was to have a page explaining in detail how to contribute questions to the database (rules, language, etc.)

Your idea of creating this page just made that 1000% better.

We don't have to worry about the content during this season, but the ultimate goal when we have it will be to have users go to this page.
