### ISSUE TITLE
Style issue with code

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#166]
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/1126730/158673633-603ca26d-7fb9-4abd-84a7-419e3d91f93e.png">

Notice how the math is rendered. It should have the same margin as the <pre> tag.

**Comment by haltakov** [comment]
The issue is that in this way you are creating an inline formula not a whole block. Try doing the following to create a block like with the \<pre\> tag.

$$
y = max(0.01 * x, 0)
$$

**Comment by svpino** [comment]
Do we want the math formulas to be centered? If that's the case, then the left margin should be aligned with the text.

Right now, we have a left margin that looks good when we are displaying code. But if we center the content, the margin looks weird.

![image](https://user-images.githubusercontent.com/1126730/158869181-6989a7b3-bcd4-48a3-96ab-08fc021bd665.png)

So I think we have 2 options:

1. No left margin, centered formulas.
2. Keep left margin, left align formulas.

What do you think?

**Comment by svpino** [comment]
Here is a full example of how it looks like

<img width="855" alt="image" src="https://user-images.githubusercontent.com/1126730/158871212-771d4b0a-b7a9-4964-9bf2-cb5039fdc819.png">
