### ISSUE TITLE
I can't select any of the answers on Chrome

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#21]
For some reason, I can't select an answer on the page when using Chrome.

The checkboxs don't work.

They do work on Safari, but not on Chrome.

Here is the link where the problem happens: https://main.d174vuemgec5wi.amplifyapp.com/

**Comment by haltakov** [comment]
Hmm, just tried it and they work on Chrome for me. What I changed yesterday is that after the question is answered, the checkboxes get disabled. Can this be the reason?

**Comment by svpino** [comment]
This might be the reason. It's weird because the question looked like it wasn't answered. 

I'm gonna close this because I think we will change the way we present the question when it was answered.
