### ISSUE TITLE
Displaying the results

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#26]
(This is a simplified version of what we did before.) 

## Transforming the choices

The first step is to replace the checkboxes as follows:

* If the option was checked, use the character `&#10095;`
* If the option was unchecked, use the character `•`

Every correct answer should be `text-green-400` regardless of whether the user checked it or not. Every incorrectly checked answer should be `text-red-400.`

Using this approach, we are answering the three questions that we care about:

1. What was the answer you submitted?
2. What is the correct answer?
3. How does the correct answer compare with the answer you submitted?

Here is an example screenshot of how this would look like (assume that options 1 and 4 were correct):

<img width="635" alt="image" src="https://user-images.githubusercontent.com/1126730/153901266-3761f1fa-e784-46f5-97e3-2dc09135c89a.png">

## Introducing the explanation

Let's use a simple message as the introduction to the explanation of a question. We could rotate this message a little bit as to not make it too monotonous.

(We probably need more ideas for the 3/4 and [0..2]/4)

### If the user got 4 out of 4

* Alright! You definitely know what you are doing!
* Good job!
* Okey-dokey! Good job!
* Keep it up!
* Keep up the good work!
* There you go!
* There you go! You definitely know what you are doing!
* You definitely know what you are doing!
* Superb!
* You made it happen!
* Hats off to you!

### If the user got 3 out of 4

* You were really close! 
* Almost got it!

### If the user got 2 or fewer out of 4

* Let's see what's going on with this question.
* Let's look at the correct answer.
* Let's work together through the answer.

Right after this message, we can display the explanation.

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/1126730/153902352-0ab0f666-5ccb-40ee-b7fe-92e936ca61b0.png">

**Comment by haltakov** [comment]
I like the general direction, but I think it is too hard to distinguish with right answers that were selected correctly and right answers that weren't selected.

I'll implement that now and will create an alternative branch with another idea I have for that.
