### ISSUE TITLE
Question's title

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#29]
Let's add "Today's question:" right above the title:

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/1126730/153910361-cd65308d-1ed6-4985-901d-f560c507837d.png">

We can also remove the performance line that is currently under the title (we moved it to the footer.)

**Comment by svpino** [comment]
Can you pull together "Today's question" and the title of the question a little bit more? Right now they are too far apart.

**Comment by haltakov** [comment]
@svpino - better like this?

https://pr-45.d174vuemgec5wi.amplifyapp.com/

**Comment by svpino** [comment]
Perfect.
