### ISSUE TITLE
The font... let's fix the font

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#30]
Alright, the font is a "me problem." The consensus is definitely that it's too large.

So I took it down a notch, and I think it's fine. I'm not sure if this will solve it, or we need to be more aggressive.

"Took it down a notch" means:

* `text-lg` went to `text-base`
* `text-2xl` went to `text-lg`
* `text-3xl` went to `text-2xl`

etc.

Can you please make the change and let me know whether this fixes it?

**Comment by haltakov** [comment]
Resolved with https://github.com/underfitted/bnomial-daily/pull/42
