### ISSUE TITLE
The API returns a new "date" attribute instead of "id"

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#32]
I made some changes in the API to ensure we are ready to have a day without a new question. (This shouldn't happen, but I wanted to make sure the API was robust to handle this case.)

The end result is the following:

* The API is not returning an `id` field anymore.
* Instead, the API is returning a `date` field indicating the date of the question.

Assuming we don't post a question on a given day, the API will return the latest question posted. 

The reason this is important is that we want to ensure we use the date returned by the API to store the answer from the user in the local storage (instead of using a date computed on the client-side.) This is probably the way it already is, but just making sure.

**Comment by haltakov** [comment]
We were using the `id` to detect a new question. I can adapt it to the `date` field. I need to change adapt the API now anyway for the new fields.
