### ISSUE TITLE
Add user friendly Loading messages

### ISSUE THREAD

**Issue by haltakov** [underfitted/bnomial-daily#35]
Currently the loading message for the question is not very nice and there is none for loading the answer

**Comment by svpino** [comment]
Maybe we want to use: "Loading today's question..." and "Cooking the results for you..."

In the future, we could look into replacing both messages with a nice animated gif or something (or maybe this is easy to do now.)

**Comment by haltakov** [comment]
What do you think about these loading messages? I'm considering using a spinner instead of the 3 dots...

https://pr-55.d174vuemgec5wi.amplifyapp.com/
