### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#56]
Since we aren't going to be using the model, I think this will make for a good favicon.

Can we vectorize it?

![icon](https://user-images.githubusercontent.com/1126730/154507535-06c6ff58-e71a-4806-8a96-61938916096f.png)

Also, it doesn't need to be precisely this one. It could be any other robot-face out there:

<img width="53" alt="image" src="https://user-images.githubusercontent.com/1126730/154507783-205c5161-c8bc-4930-a4ed-31f0d5968432.png">

**Comment by haltakov** [comment]
I think it is this one ;)

https://thenounproject.com/icon/robot-1030735/

**Comment by haltakov** [comment]
Btw. this is a great website for SVGs: https://thenounproject.com/

**Comment by svpino** [comment]
Beautiful. I didn't know about this website. Thanks for sharing!

**Comment by haltakov** [comment]
I experimented a little bit and here are some variants of the favicon. What do you think?

* Variant 1: https://pr-92.d174vuemgec5wi.amplifyapp.com/
* Variant 2: https://pr-93.d174vuemgec5wi.amplifyapp.com/
* Variant 3: https://pr-94.d174vuemgec5wi.amplifyapp.com/
* Variant 4: https://pr-95.d174vuemgec5wi.amplifyapp.com/
* Variant 5: https://pr-96.d174vuemgec5wi.amplifyapp.com/

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/300777/154867290-364b7169-ca13-4a46-bb1f-d3679824c942.png">

My favorite is variant 5.

**Comment by svpino** [comment]
I think we should be fine:

<img width="490" alt="image" src="https://user-images.githubusercontent.com/1126730/155002528-05de9ebd-5415-4089-8677-6f5d610cc4bd.png">

**Comment by haltakov** [comment]
Going with 4
