### ISSUE TITLE
Add a Tweet button to tweet the result

### ISSUE THREAD

**Issue by haltakov** [underfitted/bnomial-daily#58]
Add a button that is shown after answering the question to tweet the result and brag. Maybe we can include the current question performance as well?

**Comment by svpino** [comment]
We can show the button but change the tweet depending on the result.

If the user gets 100%:

```
I just answered today's machine learning question and got every point!

Check it out here: [link]
```

If the user doesn't get all the points:

```
Check out today's machine learning question here: [link]
```

**Comment by haltakov** [comment]
Yes, I was thinking about something like this as well.

I think we can also add something like

"67% of people answered the question correctly"

**Comment by svpino** [comment]
Good idea!

**Comment by svpino** [comment]
Let's use this text:

```
I just answered today's machine learning question and got it right!

So far, people have answered with 67% accuracy.

You can give it a try here: [link]
```
