### ISSUE TITLE
Adapt the metadata of the website

### ISSUE THREAD

**Issue by haltakov** [underfitted/bnomial-daily#66]
We need to adapt the social media metadata on the website and create a nice visual to be shown when a link is shared

**Comment by svpino** [comment]
I really like what levelsio did with remoteok.com Look at the image when he posts the link on Twitter:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/1126730/155391954-e1b4af65-86e1-433b-826c-e3644590d24e.png">

It's very "clickable". He made the image a CTA. 

Smart.
