### ISSUE TITLE
List of messages to display when the user submits an answer

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#7]
When the user submits the answer, we want to display a message to explain the results.

The **structure** will be as follows:

1. Encouriging statement
2. Summary of the correct answers
3. Explanation.

### Examples

**You were really close! You just missed one of the correct choices.**

The correct answer is:

* Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
* Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

**Let's see what's going on:**

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis tellus id interdum velit laoreet id donec ultrices. 

Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Vitae semper quis lectus nulla. Et sollicitudin ac orci phasellus egestas. Turpis egestas integer eget aliquet nibh praesent tristique. Nunc sed augue lacus viverra vitae. Odio facilisis mauris sit amet. Turpis cursus in hac habitasse platea dictumst quisque sagittis purus. 

Amet facilisis magna etiam tempor orci. Est sit amet facilisis magna. Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Netus et malesuada fames ac turpis egestas. Tristique sollicitudin nibh sit amet commodo nulla facilisi.

### About the previous example

1. We start with the encouraging statement: _"You were really close! You just missed one of the correct choices."_
2. We continue with a list with the correct answers (if more than one), or a sentence if only one correct answer.
3. We finalize with the "Let's see what's going on" section which contains the explanation.

### Encouraging statements

**Condition:** The user answers correctly.
**Message:** Alright! You definitely know what you are doing!

**Condition:** The user gets some correct choices but misses one correct choice.
**Message:** You were really close! You just missed one of the correct choices.

**Condition:** The user gets some correct choices but misses more than one correct choice.
**Message:** You were close! You just missed two of the correct choices.

**Condition:** The user doesn't get any correct choice.
**Message:** Let's review the answer together to understand what happened.

**Comment by haltakov** [comment]
This is now implemented and merged to `main`

**Comment by svpino** [comment]
A couple of changes for this:

1. Instead of "Explanation", let's put "Let's see what's going on:" It's a little bit more personal and less robotic.

2. Before getting into the explanation, let's summarize the correct answers for the user. For example:

```
The correct answer is:

* Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

* Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
```

Or, in case there's only one correct answer:

```
The correct answer is: 

* Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

```

**Comment by svpino** [comment]
I'm going to close this because I have a different idea.
