### ISSUE TITLE
Update page title

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#87]
What do you think of: 

"One machine learning question every day - bnomial"

**Comment by haltakov** [comment]
I actually like starting with bnomial, but I don't have a strong opinion on this one. I'm fine to change it.

**Comment by svpino** [comment]
I’m sorry. I should have been clearer. I was referring to the head.title of the page (browser title?)

**Comment by haltakov** [comment]
OK, I see what you mean now :)
