### ISSUE TITLE
Idea: Displaying performance and streak after the question is answered

### ISSUE THREAD

**Issue by svpino** [underfitted/bnomial-daily#88]
Right now we are displaying streak and performance in the footer.

How about displaying this information AFTER the question is answered? We could remove it from the footer and display it right below the correct answer.

Here is my reasoning:

1. It will clean the footer a little bit. It will make it simpler.'
2. It's information I want to see right after I answer the question. I feel many people will miss it as part of the footer.
3. It will make the answer a little bit less dry: we will tell you the correct answer and give you more info about how you are doing.
4. It will give us more space to explain what this info means.

What do you think?

**Comment by haltakov** [comment]
I had the first version of the stats like this, but it didn't look good as I did it. The next iteration was in the footer, which I liked more, but I agree it may be missed.

We need to think about how we display it exactly. I can try playing a bit more with this

**Comment by svpino** [comment]
Let's start with a sentence just like we have it in the footer. We can iterate from that point.

**Comment by haltakov** [comment]
Alright, here is my first proposal for this: https://pr-98.d174vuemgec5wi.amplifyapp.com/

**Comment by svpino** [comment]
How about this?

<img width="920" alt="image" src="https://user-images.githubusercontent.com/1126730/155023181-448a8672-a4e2-485c-8aa3-e6f948d90330.png">

1. Change the text
2. Use same blue color
3. Slightly modify the sentence (remove "so far")

Also, what do you think of saying "with 50% accuracy" instead of "with a performance of 50%"?

**Comment by haltakov** [comment]
Yes, I think accuracy is better.
